pymongo_auth_aws/__init__.py,sha256=vVXmWNpo2AelXeZjPr10gU0FKzLB_w3iIS7RP4xki2A,751
pymongo_auth_aws/auth.py,sha256=w6yKn6IkqMtfDEUat7-Q56lZqkHUDdXOHxavvKUTM_c,8467
pymongo_auth_aws/errors.py,sha256=ilEemepO2UD-cW5C7ZjiQWhZCmidDHlSheoWB1_2rro,725
pymongo_auth_aws/version.py,sha256=KFdyG3gagbL3Agf3NJmutlmg1m8-z4EH4Cykc7LYSic,604
pymongo_auth_aws-1.0.0.dist-info/LICENSE,sha256=xx0jnfkXJvxRnG63LTGOxlggYnIysveWIZ6H3PNdCrQ,11357
pymongo_auth_aws-1.0.0.dist-info/METADATA,sha256=GHKR_z6R-qMUR3VHuTxE0KmXH8qbXmLXVnHGXJSq-S4,4546
pymongo_auth_aws-1.0.0.dist-info/WHEEL,sha256=kGT74LWyRUZrL4VgLh6_g12IeVl_9u9ZVhadrgXZUEY,110
pymongo_auth_aws-1.0.0.dist-info/top_level.txt,sha256=P21opOPUCOCYmeePHPABoeATMGhdoQqi0BeiIRVr348,17
pymongo_auth_aws-1.0.0.dist-info/RECORD,,
